
Archived entries from file /home/cdom/.config/emacs/config.org

* 2024

** 2024-03 March

*** 2024-03-18 Monday
**** DONE File-level ~:noweb yes~ does not seem to have an effect
CLOSED: [2024-03-18 Mon 23:40]
:PROPERTIES:
:ARCHIVE_TIME: 2024-05-08 Wed 00:21
:ARCHIVE_FILE: ~/.config/emacs/config.org
:ARCHIVE_OLPATH: Anatomy/Partials/Tasks
:ARCHIVE_CATEGORY: config
:ARCHIVE_TODO: DONE
:END:

- Note taken on [2024-03-18 Mon 23:40] \\
  Turns out there was a syntax error in this line, where a arg name had a colon at the end in addition to the beginning.
- State "DONE"       from "TODO"       [2024-03-18 Mon 23:40]
Setting this on a heading works.


*** 2024-03-24 Sunday
**** CANCELLED Rename the existing feature to ~init-snippets~
CLOSED: [2024-03-24 Sun 14:44]
:PROPERTIES:
:ARCHIVE_TIME: 2024-04-08 Mon 22:11
:ARCHIVE_FILE: ~/.config/emacs/config.org
:ARCHIVE_OLPATH: Configure/Expanding Templates (~tempel~) :: ~init-templates~
:ARCHIVE_CATEGORY: config
:ARCHIVE_TODO: CANCELLED
:END:


- State "CANCELLED"  from "TODO"       [2024-03-24 Sun 14:44] \\
  "Templates" is a more correct term than "snippets".

  Templates may have placeholders to be filled and expanded.

  Snippets are static chunks of text, often "tricks" and easy-to-forget reference
  material.

  Templates may include a snippet in their expansion.  Snippets in themselves have
  no relation to templates, unless we are coincidentally talking about a snippet
  whose subject is templates.  I will say no more on that matter so that we may
  avoid further confusion.


#+name: init-templates-file
#+begin_src emacs-lisp :tangle lisp/init-templates.el :noweb yes :comments no
<<file-prop-line(feature="init-templates",desc="Expandable file templates and abbrevs")>>

;; Copyright (c) 2022-2024  Chris Montgomery <chris@cdom.io>

;; Author: Chris Montgomery <chris@cdom.io>
;; URL: https://git.sr.ht/~montchr/ceamx
;; Version: 0.1.0

<<file-license>>

;;; Commentary:
;;; Code:

<<init-templates>>

<<file-footer(feature="init-templates")>>
#+end_src
