;;; init-window-popups.el --- Popup window management  -*- lexical-binding: t; -*-

;; Copyright (C) 2024  Chris Montgomery

;; Author: Chris Montgomery <chris@cdom.io>
;; Keywords: local

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Configuration primarily for `popper'.

;;; Code:

(require 'lib-common)

;;; popper :: <https://github.com/karthink/popper>

(use-package popper
  :blackout
  :commands ( popper-mode
              popper-echo-mode
              popper-group-by-projectile
              popper-toggle
              popper-toggle-type)

  :init
  (setopt popper-reference-buffers
    '("\\*Messages\\*"
       "Output\\*$"
       "\\*Async-native-compile-log\\*"
       "\\*Compile-Log\\*"
       "\\*vc\\*"
       "\\*Warnings\\*"
       "\\*Embark Export"
       ;; TODO: not entirely sure if this pattern is correct
       "Profiler-Report"               ; report generated by `profiler' workflow
       compilation-mode
       help-mode
       helpful-mode
       +popper-current-buffer-popup-p
       ))

  (add-hook 'emacs-startup-hook #'popper-mode)
  (add-hook 'emacs-startup-hook #'popper-echo-mode)

  :config
  (define-keymap :keymap (current-global-map)
    ;; TODO: kinda difficult hand contortion
    "C-`"   #'popper-toggle
    ;; FIXME(env): Conflicts with default GNOME keybinding.
    "M-`"   #'popper-echo-mode
    "C-M-`" #'popper-toggle-type)

  ;; NOTE: A non-nil value for this setting will conflict with `shackle.el' (if
  ;; installed) and, potentially, `display-buffer-alist' customizations.
  ;; <https://github.com/karthink/popper?tab=readme-ov-file#popup-placement-controlled-using-display-buffer-alist-or-shackleel>
  (after! 'shackle
    (setopt popper-display-control nil))

  ;; Disable mode-line in popups.
  ;;
  ;; TIP: Use `buffer-name' to get a buffer's name for customization.
  (setopt popper-mode-line nil)

  (after! [projectile]
    (setopt popper-group-function #'popper-group-by-projectile)))

(provide 'init-window-popups)
;;; init-window-popups.el ends here
