;;; ceamx-user-config-news.el --- Configuration for news feed subscriptions  -*- lexical-binding: t; -*-

;; Copyright (C) 2023-2024  Chris Montgomery

;; Author: Chris Montgomery <chris@cdom.io>
;; Keywords: local, data, news

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; This list is almost as noisy as the totality of the news river.

;; TODO: I might one day find a better place for this.
;;       But here is better than `custom.el' or some init file.

;;; Code:

;; TODO: clean this up (remove all the extraneous nils inserted by `newsticker')
(defvar cmx-news-feed-url-list
    '(("Human Transit" "https://humantransit.org/feed" nil nil nil)
       ("Hacker News" "https://news.ycombinator.com/rss" nil nil nil)
       ("The Next Web" "https://feeds2.feedburner.com/thenextweb" nil nil nil)
       ("Ace Jet 170" "https://acejet170.typepad.com/foundthings/rss.xml" nil nil nil)
       ("the m john harrison blog" "https://ambientehotel.wordpress.com/feed/" nil nil nil)
       ("Bajo el Signo de Libra" "https://bajoelsignodelibra.blogspot.com/feeds/posts/default" nil nil nil)
       ("Bibliothèque Gay" "https://bibliotheque-gay.blogspot.com/feeds/posts/default" nil nil nil)
       ("Xe's Blog" "https://christine.website/blog.rss" nil nil nil)
       ("WP Tavern" "https://wptavern.com/feed/json" nil nil nil)
       ("Naked Philly Blog Posts Archive - OCF Realty" "https://www.ocfrealty.com/naked-philly/feed/" nil nil nil)
       ("Bullet Journal - The Bullet Journalist" "https://bulletjournal.com/blogs/bulletjournalist.atom" nil nil nil)
       ("mediapathic" "https://mediapathic.blot.im/feed.rss" nil nil nil)
       ("Infodump" "https://infodump.ghost.io/rss/" nil nil nil)
       ("New Models" "http://feeds.feedburner.com/newmodels/rss" nil nil nil)
       ("ribbonfarm" "https://www.ribbonfarm.com/feed/" nil nil nil)
       ("⁂" "https://annaxmalina.tumblr.com/rss" nil nil nil)
       ("Rev Dan Catt" "https://revdancatt.com/rss" nil nil nil)
       ("BLDGBLOG" "https://bldgblog.com/feed/" nil nil nil)
       ("Articles - Tiny Ray of Sunshine" "https://www.tinyrayofsunshine.com/blog?format=rss" nil nil nil)
       ("Kensington Voice" "https://kensingtonvoice.com/en/feed/" nil nil nil)
       ("IndieWire" "https://www.indiewire.com/feed/" nil nil nil)
       ("n+1Articles – n+1" "https://www.nplusonemag.com/feed/" nil nil nil)
       ("And now it’s all this" "https://leancrew.com/all-this/feed/" nil nil nil)
       ("Stories by Coalition for Critical Technology on Medium" "https://medium.com/feed/@CoalitionForCriticalTechnology" nil nil nil)
       ("but she's a girl..." "https://www.rousette.org.uk/index.xml" nil nil nil)
       ("Funky Penguin's Geek Cookbook" "https://mastodon.social/@geekcookbook_changes.rss" nil nil nil)
       ("Circle of Peacemakers" "https://peacemaker.design.blog/feed/" nil nil nil)
       ("The Trace" "https://www.thetrace.org/feed/" nil nil nil)
       ("Sacha Chua" "https://sachachua.com/blog/feed/" nil nil nil)
       ("Jethro Kuan" "https://blog.jethro.dev/index.xml" nil nil nil)
       ("Three Word Phrase" "http://www.threewordphrase.com/rss.xml" nil nil nil)
       ("Saturday Morning Breakfast Cereal" "https://www.smbc-comics.com/comic/rss" nil nil nil)
       ("Juniata News" "https://juniatanewsphilly.wordpress.com/feed/" nil nil nil)
       ("Stan's blog" "https://stanislas.blog/atom.xml" nil nil nil)
       ("Tweag - Nix blog" "https://www.tweag.io/rss-nix.xml" nil nil nil)
       ("Tweag - Engineering blog" "https://www.tweag.io/rss.xml" nil nil nil)
       ("InfoQ" "https://feed.infoq.com/" nil nil nil)
       ("Dans Blog" "https://www.dantleech.com/atom.xml" nil nil nil)
       ("d12frosted" "https://d12frosted.io/atom.xml" nil nil nil)
       ("Drew DeVault's blog" "https://drewdevault.com/blog/index.xml" nil nil nil)
       ("Coding Horror" "https://blog.codinghorror.com/rss/" nil nil nil)
       ("TorrentFreak" "https://torrentfreak.com/feed/" nil nil nil)
       ("The GitHub Blog" "https://github.blog/feed/" nil nil nil)
       ("Xah Emacs Blog" "http://ergoemacs.org/emacs/blog.xml" nil nil nil)
       ("Emacs café" "https://emacs.cafe/feed.xml" nil nil nil)
       ("Alvaro Ramirez's notes" "https://xenodium.com/rss.xml" nil nil nil)
       ("Krebs on Security" "https://krebsonsecurity.com/feed/" nil nil nil)
       ("Schneier on Security" "https://www.schneier.com/feed/atom/" nil nil nil)
       ("Giant Robots Smashing Into Other Giant Robots" "https://feeds.feedburner.com/GiantRobotsSmashingIntoOtherGiantRobots" nil nil nil)
       ("The Record from Recorded Future News" "https://therecord.media/feed/" nil nil nil)
       ("Calum MacRae on" "https://cmacr.ae/index.xml" nil nil nil)
       ("Damn Interesting" "https://feeds.feedburner.com/damninteresting/all" nil nil nil)
       ("Tech.ToryAnderson.com" "https://tech.toryanderson.com/index.xml" nil nil nil)
       ("Emacsair" "https://emacsair.me/feed.xml" nil nil nil)
       ("Where parallels cross" "https://ag91.github.io/rss.xml" nil nil nil)
       ("Bret Victor's website" "http://worrydream.com/feed.xml" nil nil nil)
       ("ACM Queue - All Queue Content" "https://queue.acm.org/rss/feeds/queuecontent.xml" nil nil nil)
       ("Frantic Notes" "https://blog.frantic.im/rss/" nil nil nil)
       ("The MIT Press Reader" "https://thereader.mitpress.mit.edu/feed/" nil nil nil)
       ("NN/g latest articles and announcements" "https://www.nngroup.com/feed/rss/" nil nil nil)
       ("Ahmad Shadeed Blog" "https://ishadeed.com/feed.xml" nil nil nil)
       ("Murilo Pereira" "https://www.murilopereira.com/index.xml" nil nil nil)
       ("Posts on tychoish" "https://tychoish.com/post/index.xml" nil nil nil)
       ("Farid Zakaria’s Blog" "https://fzakaria.com/feed.xml" nil nil nil)
       ("Graham Christensen" "https://grahamc.com/feed/" nil nil nil)
       ("esoteric.codes" "https://esoteric.codes/rss" nil nil nil)
       ("Arch Linux: Recent news updates" "https://archlinux.org/feeds/news/" nil nil nil)
       ("Brian Di Croce" "https://briandicroce.com/feed/" nil nil nil)
       ("(think)" "https://batsov.com/atom.xml" nil nil nil)
       ("Martin Fowler" "https://martinfowler.com/feed.atom" nil nil nil)
       ("Daring Fireball" "https://daringfireball.net/feeds/main" nil nil nil)
       ("BleepingComputer" "https://www.bleepingcomputer.com/feed/" nil nil nil)
       ("unixsheikh.com" "https://unixsheikh.com/feed.rss" nil nil nil)
       ("Planet Emacslife" "https://planet.emacslife.com/atom.xml" nil nil nil)
       ("Dan Luu" "https://danluu.com/atom.xml" nil nil nil)
       ("Josh Comeau's blog" "https://www.joshwcomeau.com/rss.xml" nil nil nil)
       ("Posts on Seirdy's Home" "https://seirdy.one/posts/index.xml" nil nil nil)
       ("Trivium" "https://leahneukirchen.org/trivium/index.atom" nil nil nil)
       ("Blog - giCentre" "https://www.gicentre.net/blog?format=rss" nil nil nil)
       ("indieblog.page daily random posts" "https://indieblog.page/dailyfeed" nil nil nil)
       ("Geotripper" "https://geotripper.blogspot.com/feeds/posts/default" nil nil nil)
       ("Feed" "https://samleathers.com/feed.xml" nil nil nil)
       ("./techtipsy" "https://ounapuu.ee/index.xml" nil nil nil)
       ("Blogs on Sourcehut" "https://sourcehut.org/blog/index.xml" nil nil nil)
       ("KISS Linux Posts" "https://kisslinux.org/rss/post.rss" nil nil nil)
       ("KISS Linux Tidbits" "https://kisslinux.org/rss/tidbits.rss" nil nil nil)
       ("astrid.tech" "https://astrid.tech/atom.xml" nil nil nil)
       ("tonsky.me" "https://tonsky.me/blog/atom.xml" nil nil nil)
       ("Uses This" "https://usesthis.com/feed.atom" nil nil nil)
       ("bitonic's blog." "https://mazzo.li/rss.xml" nil nil nil)
       ("Ars Technica - All content" "http://feeds.arstechnica.com/arstechnica/index/" nil nil nil)
       ("precondition" "https://precondition.github.io/feed.xml" nil nil nil)
       ("Shadowfacts" "https://shadowfacts.net/feed.xml" nil nil nil)
       ("Emacs TIL" "https://emacstil.com/feed.xml" nil nil nil)
       ("Frontend Focus" "https://cprss.s3.amazonaws.com/frontendfoc.us.xml" nil nil nil)
       ("CSS Weekly" "http://feeds.feedburner.com/CSS-Weekly?format=xml" nil nil nil)
       ("Solene'%" "https://dataswamp.org/~solene/rss.xml" nil nil nil)
       ("Privacy and Security News Archives | RestorePrivacy" "https://restoreprivacy.com/category/news-reports/feed/" nil nil nil)
       ("Ctrl blog" "https://feed.ctrl.blog/latest.atom" nil nil nil)
       ("Blog posts by Will Grant" "https://blog.willgrant.org/feed.xml" nil nil nil)
       ("web.dev" "https://web.dev/feed.xml" nil nil nil)
       ("Read the Tea Leaves" "https://nolanlawson.com/feed/" nil nil nil)
       ("Doeke Norg - I like talking about PHP" "https://doeken.org/blog/feed.atom" nil nil nil)
       ("Adactio: Links" "https://adactio.com/links/rss" nil nil nil)
       ("Adactio: Articles" "https://adactio.com/articles/rss" nil nil nil)
       ("Latest News from thePHP.cc" "https://thephp.cc/feeds/news/latest.xml" nil nil nil)
       ("Astral Codex Ten" "https://astralcodexten.substack.com/feed" nil nil nil)
       ("project-insanity.org" "https://blog.project-insanity.org/feed/" nil nil nil)
       ("j3s.sh" "https://j3s.sh/feed.atom" nil nil nil)
       ("jonas's blog" "https://jonascarpay.com/rss.xml" nil nil nil)
       ("CSS-Tricks" "https://css-tricks.com/feed/" nil nil nil)
       ("gay robot noises - /var/log/ash" "https://catgirl.ai/log/atom.xml" nil nil nil)
       ("Technomancy" "https://technomancy.us/atom.xml" nil nil nil)
       ("Anil Dash" "https://feeds.dashes.com/AnilDash" nil nil nil)
       ("Rands in Repose" "http://randsinrepose.com/feed/" nil nil nil)
       ("kottke.org" "http://feeds.kottke.org/main" nil nil nil)
       ("The Awl" "http://feeds2.feedburner.com/TheAwl" nil nil nil)
       ("what if?" "https://what-if.xkcd.com/feed.atom" nil nil nil)
       ("Marco.org" "https://marco.org/rss" nil nil nil)
       ("MacStories" "https://www.macstories.net/feed/" nil nil nil)
       ("Sounds of the Dawn's YouTube Videos" "https://www.youtube.com/feeds/videos.xml?channel_id=UC7brSEzOeLLb0l3QhAtdkgw" nil nil nil)
       ("Music For Programming" "https://musicforprogramming.net/rss.php/" nil nil nil)
       ("mudd up!" "https://www.negrophonic.com/feed/" nil nil nil)
       ("Hidden City Philadelphia" "https://hiddencityphila.org/feed/" nil nil nil)
       ("A List Apart: The Full Feed" "https://alistapart.com/main/feed/" nil nil nil)
       ("{ feuilleton }" "https://www.johncoulthart.com/feuilleton/feed/" nil nil nil)
       ("xkcd.com" "https://xkcd.com/rss.xml" nil nil nil)
       ("Dinosaur Comics!" "https://qwantz.com/rssfeed.php" nil nil nil)
       ("BLDGBLOG" "http://bldgblog.blogspot.com/feeds/posts/default" nil nil nil)
       ("Scarfolk Council" "https://scarfolk.blogspot.com/feeds/posts/default" nil nil nil)
       ("Columbia Journalism Review" "http://www.cjr.org/atom.xml" nil nil nil)
       ("trms" "https://trms.me/feed/" nil nil nil)
       ("Laravel News" "https://feed.laravel-news.com/" nil nil nil)
       ("WordPress Developer Blog" "https://developer.wordpress.org/news/feed/" nil nil nil)
       ("Sharing what we learn about the responsive web – Cloud Four" "https://feeds.feedburner.com/cloudfour" nil nil nil)
       ("Rachel Andrew" "https://rachelandrew.co.uk/feed/" nil nil nil)
       ("Adrian Roselli" "https://adrianroselli.com/feed" nil nil nil)
       ("Tom J Nowell" "https://tomjn.com/feed/" nil nil nil)
       ("La Quadrature du Net" "https://www.laquadrature.net/en/feed/" nil nil nil)
       ("Rich Tabor" "https://richtabor.com/feed/" nil nil nil)
       ("gutenberg-new – Make WordPress Core" "https://make.wordpress.org/core/tag/gutenberg-new/feed/" nil nil nil)
       ("gutenberg-themes-roundup – Make WordPress Themes" "https://make.wordpress.org/themes/tags/gutenberg-themes-roundup/feed/" nil nil nil)
       ("Blog on Thomas Kräftner" "https://kraftner.com/en/blog/index.xml" nil nil nil)
       ("Tom McFarlin" "https://tommcfarlin.com/feed/" nil nil nil)
       ("Posts on theAverageDev" "https://theaveragedev.com/posts/index.xml" nil nil nil)
       ("Max Design articles" "https://www.maxdesign.com.au/" nil nil nil)
       ("Domain Incite" "http://domainincite.com/feed" nil nil nil)
       ("Brainwashed Radio - The Podcast Edition" "https://brainwashed.com/podcast/podcast_rss.xml" nil nil nil)
       ("Music" "https://brainwashed.com/index.php/reviews-easyblog?format=feed&type=rss" nil nil nil)
       ("Drake Rossman's Website" "https://drakerossman.com/feed.xml" nil nil nil)
       ("stitcher.io" "https://stitcher.io/rss" nil nil nil)
       ("Pluralistic: Daily links from Cory Doctorow" "https://pluralistic.net/feed/" nil nil nil)
       ("Softwares on Karthinks" "https://karthinks.com/software/index.xml" nil nil nil)))


(provide 'ceamx-user-config-news)
;;; ceamx-user-config-news.el ends here
